import 'package:equatable/equatable.dart';

import 'event.dart';

/// A request model for creating a new event in the system.
///
/// This class contains all necessary information to create an event
/// but omits fields that would be generated by the backend such as
/// IDs, creation timestamps, and cancellation status.
class CreateEventRequest extends Equatable {
  // Event identification
  final String title;
  final String subtitle;
  final String courseId;

  // Event host info
  final String hostName;

  // Event type and mode
  final EventType eventType;
  final EventMode eventMode;

  // Timing information
  final DateTime startTime;
  final DateTime endTime;
  final RecurringType recurringType;
  final DateTime? recurringEndDate;

  // Location details
  final String? buildingId;
  final String? roomId;
  final String? onlineLink;

  // Additional information
  final String? description;

  /// Creates a new event creation request.
  ///
  /// Required parameters include basic event details, host information,
  /// event type/mode, and timing information. Location details depend on
  /// the [eventMode] selected (physical or online).
  const CreateEventRequest({
    // Event identification
    required this.title,
    required this.subtitle,
    required this.courseId,

    // Event host info
    required this.hostName,

    // Event type and mode
    required this.eventType,
    required this.eventMode,

    // Timing information
    required this.startTime,
    required this.endTime,
    required this.recurringType,
    this.recurringEndDate,

    // Location details
    this.buildingId,
    this.roomId,
    this.onlineLink,

    // Additional information
    this.description,
  });

  @override
  List<Object?> get props => [
    // Event identification
    title, subtitle, courseId,
    // Event host info
    hostName,
    // Event type and mode
    eventType, eventMode,
    // Timing information
    startTime, endTime, recurringType, recurringEndDate,
    // Location details
    buildingId, roomId, onlineLink,
    // Additional information
    description
  ];
}